version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    network_mode: host

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    network_mode: host
