services:
  db:
    image: mariadb:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: pigeon
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./db-data:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql

  backend:
    build:
      context: api
      additional_contexts:
        - parent=.
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DB_URL: mysql://root:${MYSQL_ROOT_PASSWORD}@db:3306/pigeon
    ports:
      - "${BACKEND_PORT}:8081"
    depends_on:
      - db

  frontend:
    build:
      context: app
      args:
        VUE_APP_API_URL: http://localhost:${BACKEND_PORT}
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:8080"
    depends_on:
      - backend

volumes:
  db-data: