name: CI - Run Backend Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: cp example.env .env

      - name: Set up Docker Compose
        run: docker compose up -d db backend

      - name: Run tests in backend container
        run: docker exec backend npm test

      - name: Tear down Docker Compose
        if: always()
        run: docker-compose down
