name: CI - Run Backend Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup docker env
        run: |
          echo "MYSQL_ROOT_PASSWORD=test" > .env
          echo "DB_PORT=3306" >> .env

      - name: Start database container
        run: docker compose up -d db

      - name: Navigate to API folder and create .env file
        run: |
          cd api
          echo "DB_URL=mysql://root:test@localhost:3306/pigeon" > .env
          echo "ACCESS_TOKEN_SECRET=test" >> .env
          echo "REFRESH_TOKEN_SECRET=test" >> .env

      - name: Install dependencies
        run: |
          cd api
          npm install

      - name: Run tests
        run: |
          cd api
          npm run test:no-reloading

      - name: Tear down database container
        if: always()
        run: docker-compose down
